# -*- coding: utf-8 -*-
"""basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TiUpYGPmwomTQvLvAwswRLxarcvBqgW-
"""

print("hello world");